export const text = {
	stat: {
		dps: 'DPS',
		dpc: 'DPC',
		pa: 'PA',
		pm: 'PM',
		vit: 'Vitalidad',
		str: 'Fuerza',
		int: 'Inteligencia',
		cha: 'Suerte',
		agi: 'Agilidad',
		speDmg: '% Daño hechizo',
		wepDmg: '% Daño arma',
		res: '% Resistencia',
		reDmg: '% Reenvío',
		pot: 'Potencia',
		strDmg: 'Daño tierra',
		intDmg: 'Daño fuego',
		chaDmg: 'Daño agua',
		agiDmg: 'Daño aire',
		dmg: 'Daños',
		crt: '% Crítico',
		crtDmg: 'Daño crítico',
		wis: 'Sabiduria',
		cur: 'Curas',
		al: 'Lucidez',
		pp: 'Prospección',
		invo: 'Bestialidad',
	},
	element: {
		earth: 'Tierra',
		fire: 'Fuego',
		water: 'Agua',
		air: 'Aire',
	}
}