export const text = {
	stat: {
		dps: 'DPS',
		dpc: 'DPC',
		pa: 'PA',
		pm: 'PM',
		vit: 'Vitalidad',
		str: 'Fuerza',
		int: 'Inteligencia',
		cha: 'Suerte',
		agi: 'Agilidad',
		paReg: 'Subida PA',
		pmReg: 'Subida PM',
		pot: 'Potencia',
		strDmg: 'Daño tierra',
		intDmg: 'Daño fuego',
		chaDmg: 'Daño agua',
		agiDmg: 'Daño aire',
		dmg: 'Daños',
		crt: '% Crítico',
		crtDmg: 'Daño crítico',
		wis: 'Sabiduria',
		cur: 'Curas',
		al: 'Lucidez',
		pp: 'Prospección',
		invo: 'Bestialidad',
	}
}